/**
 * Bundled circuit outlines, one JSON per OpenF1 `circuit_key`, generated by
 * `make outlines` (see README.md in this directory).
 *
 * `import.meta.glob` makes each outline its own lazily-loaded chunk, so the
 * app ships all circuits without loading any until a session names one.
 */

export interface Outline {
  circuit_key: number
  circuit_short_name: string | null
  source_session_key: number
  /** The season the source session ran in; may predate the current one. */
  source_year?: number | null
  generated_at?: string
  points: [number, number][]
}

const modules = import.meta.glob<{ default: Outline }>('./*.json')

export function hasOutline(circuitKey: number | null | undefined): boolean {
  return circuitKey != null && `./${circuitKey}.json` in modules
}

export async function loadOutline(circuitKey: number | null | undefined): Promise<Outline | null> {
  if (circuitKey == null) return null
  const loader = modules[`./${circuitKey}.json`]
  if (!loader) return null
  const module = await loader()
  return module.default
}
