import { beforeEach, describe, expect, it } from 'vitest'
import { render, screen, within } from '@testing-library/react'
import { Leaderboard } from './Leaderboard'
import { StatusStrip } from './StatusStrip'
import { useStore } from '../store'
import type { SessionState } from '../types/sessionState'
import sampleSnapshot from '../test/sampleSnapshot.json'

/**
 * Phase 2 acceptance test.
 *
 * The fixture is not hand-written: it is generated by the backend
 * (`make types`) by feeding sample messages through the real OpenF1LiveSource
 * and serialising the resulting SessionState. So this renders exactly the bytes
 * the backend would send, and a backend test fails if the fixture goes stale.
 *
 * The sample deliberately includes lap 12 delivered twice under one `_key`,
 * which is the upsert case the OpenF1 docs call out.
 */

const snapshot = sampleSnapshot as unknown as SessionState

function inject(state: SessionState = snapshot) {
  useStore.setState({ snapshot: state, status: 'open', lastMessageAt: Date.now() })
}

function rowFor(acronym: string): HTMLElement {
  const cell = screen.getByText(acronym)
  const row = cell.closest('tr')
  if (!row) throw new Error(`no row for ${acronym}`)
  return row
}

/** One column of one row. LAST and BEST often hold the same text. */
function cell(acronym: string, column: string): HTMLElement {
  const found = rowFor(acronym).querySelector(`td[data-col="${column}"]`)
  if (!found) throw new Error(`no ${column} cell for ${acronym}`)
  return found as HTMLElement
}

beforeEach(() => {
  useStore.setState({ snapshot: null, status: 'connecting', lastMessageAt: null })
})

describe('Leaderboard', () => {
  it('renders 20-plus drivers', () => {
    inject()
    render(<Leaderboard />)
    // One row per driver, plus the header row.
    expect(screen.getAllByRole('row')).toHaveLength(snapshot.drivers.length + 1)
    expect(snapshot.drivers.length).toBeGreaterThanOrEqual(20)
  })

  it('renders every Tier A column and no DRS column', () => {
    inject()
    render(<Leaderboard />)
    for (const heading of ['Pos', 'Driver', 'Tyre', 'Last', 'Best', 'Gap', 'Int', 'Pit']) {
      expect(screen.getByRole('columnheader', { name: heading })).toBeInTheDocument()
    }
    // 2026 has no DRS. These must not exist anywhere, in any casing.
    expect(screen.queryByText(/drs/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/^aero$/i)).not.toBeInTheDocument()
    expect(screen.queryByText(/^ot$/i)).not.toBeInTheDocument()
  })

  it('orders rows by position', () => {
    inject()
    render(<Leaderboard />)
    const rows = screen.getAllByRole('row').slice(1)
    const positions = rows.map((row) => row.querySelector('td')?.textContent)
    expect(positions.slice(0, 5)).toEqual(['1', '2', '3', '4', '5'])
  })

  it('shows the updated lap value from the second message with the same _key', () => {
    inject()
    render(<Leaderboard />)
    // Lap 12 first arrived with only sector 1 and a null duration, then was
    // revised to 79.681. The revision is what must be on screen.
    expect(cell('VER', 'last')).toHaveTextContent('1:19.681')
  })

  it('applies team colours from the API', () => {
    inject()
    render(<Leaderboard />)
    const bar = rowFor('VER').querySelector('td div[aria-hidden]') as HTMLElement
    expect(bar).toHaveStyle({ backgroundColor: '#4781D7' })
  })

  it('falls back to teams.ts when the API sends no colour', () => {
    inject()
    render(<Leaderboard />)
    // Audi has team_colour: null in the fixture.
    const audi = snapshot.drivers.find((d) => d.team_name === 'Audi')
    expect(audi?.team_colour).toBeNull()
    const bar = rowFor(audi!.name_acronym!).querySelector('td div[aria-hidden]') as HTMLElement
    expect(bar).toHaveStyle({ backgroundColor: '#00E701' })
  })

  it('shows LEADER for P1 and a formatted gap for the rest', () => {
    inject()
    render(<Leaderboard />)
    expect(cell('VER', 'gap')).toHaveTextContent('LEADER')
    expect(cell('LAW', 'gap')).toHaveTextContent('+0.340')
  })

  it('passes through the lapped-car gap string', () => {
    inject()
    render(<Leaderboard />)
    const last = snapshot.drivers[snapshot.drivers.length - 1]
    expect(cell(last.name_acronym!, 'gap')).toHaveTextContent('+1 LAP')
  })

  it('shows tyre compound and age', () => {
    inject()
    render(<Leaderboard />)
    const row = within(rowFor('VER'))
    expect(row.getByRole('img', { name: 'Medium' })).toBeInTheDocument()
    expect(row.getByText('7L')).toBeInTheDocument()
  })

  it('flags a car in the pits and a car on an out-lap', () => {
    inject()
    render(<Leaderboard />)
    const pitting = snapshot.drivers.find((d) => d.in_pit)!
    const outLap = snapshot.drivers.find((d) => d.is_pit_out_lap && !d.in_pit)!
    expect(within(rowFor(pitting.name_acronym!)).getByText('PIT')).toBeInTheDocument()
    expect(within(rowFor(outLap.name_acronym!)).getByText('OUT')).toBeInTheDocument()
  })

  it('colours the session best purple and a slower lap yellow', () => {
    inject()
    render(<Leaderboard />)
    // VER holds the session best, so their LAST cell is purple.
    expect(cell('VER', 'last').className).toContain('text-timing-best')

    // A driver whose last lap is slower than their own best: LAST is yellow
    // while BEST stays green, which is the whole point of the two colours.
    const slower = snapshot.drivers.find(
      (d) => d.last_lap_duration && d.best_lap_duration && d.last_lap_duration > d.best_lap_duration,
    )!
    expect(cell(slower.name_acronym!, 'last').className).toContain('text-timing-slower')
    expect(cell(slower.name_acronym!, 'best').className).toContain('text-timing-personal')
  })

  it('shows a helpful message rather than an empty table before data arrives', () => {
    render(<Leaderboard />)
    expect(screen.getByText('No timing data yet')).toBeInTheDocument()
    expect(screen.queryByRole('table')).not.toBeInTheDocument()
  })
})

describe('StatusStrip', () => {
  it('shows the session, the flag and a LIVE badge', () => {
    inject()
    render(<StatusStrip />)
    expect(screen.getByText('Practice 1')).toBeInTheDocument()
    expect(screen.getByText('Monza')).toBeInTheDocument()
    expect(screen.getByText('YELLOW')).toBeInTheDocument()
    expect(screen.getByText('LIVE')).toBeInTheDocument()
  })

  it('shows a fresh data age', () => {
    inject()
    render(<StatusStrip />)
    expect(screen.getByText('Data age')).toBeInTheDocument()
    expect(screen.getByText('0s')).toBeInTheDocument()
  })

  it('reports OFFLINE when the socket is closed', () => {
    useStore.setState({ snapshot, status: 'closed', lastMessageAt: Date.now() })
    render(<StatusStrip />)
    expect(screen.getByText('OFFLINE')).toBeInTheDocument()
    expect(screen.queryByText('LIVE')).not.toBeInTheDocument()
  })

  it('does not show the partial aero badge unless race control enables it', () => {
    inject()
    render(<StatusStrip />)
    expect(screen.queryByText('PARTIAL AERO')).not.toBeInTheDocument()
  })

  it('shows the partial aero badge when race control enables it', () => {
    inject({ ...snapshot, partial_aero: true })
    render(<StatusStrip />)
    expect(screen.getByText('PARTIAL AERO')).toBeInTheDocument()
  })
})
